# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306bae807ea836fe122ca05917b35514b47db5cde53c394c0aab038c4e56fa4c678226892155e580998b7077d6d2f944843aea6c343a3d69cb43f7e599840219

test:
  secret_key_base: ed1af26bd44fc00f49bec70201ff839962a965a04cbb4e7923ebe1f4e2e8806503cae82eb92f28d8b42298ed508c534521c1e64391ba07cb7115232c614a5c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
